<?php
// Author: Hyunjoon Lim, Suyeon Lim
// Title:  Fine dust openAPI server
// Date: May-06-2018
// License: Star License
//
// Description: This webpage is to display weather and user schedule
// The below statements do not make a PHP debug message to show parse errors.
// In case of PHP7/Ubuntu 16.04, the only way to show those errors is to

// Modify "/etc/php/7.0/apache2/php.ini" file with "display_errors = On" for debugging.

// Airkorea OpenAPI: Korean Air Quality API:
// 0. https://www.data.go.kr/dataset/15000581/openapi.do
// 1. http://openapi.airkorea.or.kr/openapi/services/rest/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty?sidoName=서울&pageNo=1&numOfRows=10&ServiceKey=<your_auth_key>&ver=1.3
// 2. https://api.waqi.info/feed/geo:37.517530;126.719561/?token=41da8ebfbc9cc68442af347291689e8cbeb5a9b1
// @author: Suyeon Lim
// @date  : Jun-07-2018
// @memo  : WARNING!!!. Fine dust API server responses until 200 request. So we refresh per 10 minutes.
// ---------- Configuration-----------------------------------------------------------
$city_name="서울";
$my_city="강남구";
// API Key is generated by leemgs, 2018/06/04 23:42:28 , for 24 months
// $dust_api_key="SIWaWSrBVuPLMIiRMgaD7%2FZFYT4xEQwqDTG67Nkk1HiO3xxpvCYu2hXU%2FK7%2Fuk3jiKS2LxIGSgz4%2FmVHCs1Y%2FA%3D%3D";
// API Key is generated by hjoon0510, 2018/06/23 15:33:26, for 24 months
$dust_api_key="nVZ4Etly2opoB1u%2B8Y%2BuV3wcGlm75tl3BzC2%2FqUiGzFEnKuVV21oa%2FdYm%2BbI6o0oeeMzn5kuqtRhaxbaz5R4zg%3D%3D";
$fine_dust_ver="1.3";

// ---------- Do not modify from now on ----------------------------------------------
// Airkorea OpenAPI: Korean Air Quality API
// We can use Open API Service from airkorea.or.kr.
// For more detail, visit https://www.data.go.kr/dataset/15000581/openapi.do. Then, read Page 17 of the manual.
$url_base = "http://openapi.airkorea.or.kr/openapi/services/rest/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty";
$url_full = "$url_base?sidoName=${city_name}&pageNo=1&numOfRows=30&ServiceKey=${dust_api_key}&ver=${fine_dust_ver}";

// Use XML format to get the fine dust information
// If we have to get data with json format, we have to append "&_returnType=json" parameter behind $url_full.
// http://php.net/manual/kr/function.file-get-contents.php
// http://php.net/manual/kr/function.simplexml-load-string.php
$contents = file_get_contents($url_full); // get contents from api server
$xml=simplexml_load_string($contents); // get data with xml format
$obj_addr=$xml->body[0]->items[0];  // item[0]

// If openapi.airkorea.or.kr does not work, let's display debug message.
if ($obj_addr == "") {
    echo "<br><br>";
    echo "[DEBUG] Response of API Server (http://openapi.airkorea.or.kr):<br>";
    echo "[DEBUG] <font color=red>".$xml->header->resultMsg."</font><br>";
    return 0;
}

// find a fine dust value of my city.
// http://php.net/manual/en/control-structures.foreach.php
foreach($obj_addr->item as $value) {
    // let's display only my city among the cities.
    // pm10Grade1H : Particulate Matter, 미세먼지, 1시간 등급
    // pm2.5Grade1H: Particulate Matter, 초미세먼지, 1시간 등급
    //echo "<b>Real-time inquiry of air pollution information</b><br>";
    //echo "<font color=red>Grade: 1(very good), 2(good), 3(bad), 4(worse)</font><br><br>";
        if ($value->stationName == $my_city){
        // echo "dataTime   :".$value->dataTime."<br>";
        // echo "stationNmae:".$value->stationName."<br>";
        // echo "mangName   :".$value->mangName."<br>" ;
        // echo "pm10Grade1h:".$value->pm10Grade1h."<br>";
        //echo "o3Grade    :".$value->o3Grade."<br>";
        // echo "----------------------------------------<br>";
        // let's create ./data/current_finedust.txt file for PIR sensor.
        system ("echo  $value->pm10Grade1h > ./data/current_finedust.txt");
      break;
    }
}

?>

